version: '3'
services:
  mongodb:
    restart: always
    container_name: mongo
    image: mongo
    volumes:
      - ./.data:/data/db
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin0091